### ISSUE TITLE
Portal functioneert (nog) niet goed als ik docker-compose gebruik

### ISSUE THREAD

**Issue by sgort** [OpenCatalogi/.github#428]
Mbv onderstaande `docker-compose.yml file` draai ik open catalogi **accepatie** omgeving op

- https://nextcloud-acc.open-regels.nl/apps/openregister/
- https://opencatalogi-acc.open-regels.nl/

De portal functioneert echter niet goed. Zie screenshot onderaan... Ik heb een CORS unblock extensie aan staan. Anders komen de pages en menus sowieso niet door.

```
volumes:
  nextcloud:
  apps:
  db:
  config:

services:
  portal:
    image: acatonl/woo-ui-develop
    ports:
    - "8081:80"

  catalog:
    image: ghcr.io/opencatalogi/web-app:dev
    ports:
    - "8082:8080"

  woo:
    image: ghcr.io/conductionnl/woo-website:dev
    ports:
    - "8083:8080"

  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW --skip_networking=0 --skip-grant-tables
    volumes:
      - db:/var/lib/mysql
    ports:
    - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MYSQL_TCP_PORT=3306
      - MARIADB_AUTO_UPGRADE=1
      - MYSQL_UNIX_PORT=/run/mysqld/mysqld.sock
      - MARIADB_MYSQL_LOCALHOST_USER=true
    expose:
      - 3306

  nextcloud:
    user: root
    container_name: nextcloud
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html:rw
      - ./custom_apps:/var/www/html/custom_apps
    environment:
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud-acc.open-regels.nl 192.168.2.68
      - OVERWRITEPROTOCOL=https
      - TZ=Europe/Amsterdam
 ```

![Image](https://github.com/user-attachments/assets/78e08c0e-8071-4011-9aaf-10daf40f6d64)
